apiVersion: apps/v1
kind: Deployment
metadata:
  name: omke
spec:
  replicas: 1
  selector:
    matchLabels:
      app: omke
  template:
    metadata:
      labels:
        app: omke
    spec:
      containers:
      - image: okteto.dev/omke:latest
        name: omke
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "45eea729-91cc-4310-8072-31e3cb93252f"
        - name: Vless_Path
          value: "/45eea729-91cc-4310-8072-31e3cb93252f"
        - name: Vmess_UUID
          value: "2a8f5bbf-fe67-4e3d-9d06-ebd088cce9f3"
        - name: Vmess_Path
          value: "/2a8f5bbf-fe67-4e3d-9d06-ebd088cce9f3"
        - name: Share_Path
          value: "/v2link"
